/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmarildoHysaRouteImport } from './routes/amarildo-hysa'
import { Route as AppRouteImport } from './routes/app'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RrethRouteImport } from './routes/rreth'
import { Route as ShkarkoRouteImport } from './routes/shkarko'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSpeakRouteImport } from './routes/api/speak'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiZeriChatRouteImport } from './routes/api/zeri-chat'
import { Route as ApiZeriTtsRouteImport } from './routes/api/zeri-tts'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmarildoHysaRoute = AmarildoHysaRouteImport.update({
  id: '/amarildo-hysa',
  path: '/amarildo-hysa',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RrethRoute = RrethRouteImport.update({
  id: '/rreth',
  path: '/rreth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShkarkoRoute = ShkarkoRouteImport.update({
  id: '/shkarko',
  path: '/shkarko',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeakRoute = ApiSpeakRouteImport.update({
  id: '/api/speak',
  path: '/api/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeriChatRoute = ApiZeriChatRouteImport.update({
  id: '/api/zeri-chat',
  path: '/api/zeri-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeriTtsRoute = ApiZeriTtsRouteImport.update({
  id: '/api/zeri-tts',
  path: '/api/zeri-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amarildo-hysa': typeof AmarildoHysaRoute
  '/app': typeof AppRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rreth': typeof RrethRoute
  '/shkarko': typeof ShkarkoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/version': typeof ApiVersionRoute
  '/api/zeri-chat': typeof ApiZeriChatRoute
  '/api/zeri-tts': typeof ApiZeriTtsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amarildo-hysa': typeof AmarildoHysaRoute
  '/app': typeof AppRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rreth': typeof RrethRoute
  '/shkarko': typeof ShkarkoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/version': typeof ApiVersionRoute
  '/api/zeri-chat': typeof ApiZeriChatRoute
  '/api/zeri-tts': typeof ApiZeriTtsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amarildo-hysa': typeof AmarildoHysaRoute
  '/app': typeof AppRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rreth': typeof RrethRoute
  '/shkarko': typeof ShkarkoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/version': typeof ApiVersionRoute
  '/api/zeri-chat': typeof ApiZeriChatRoute
  '/api/zeri-tts': typeof ApiZeriTtsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amarildo-hysa'
    | '/app'
    | '/links'
    | '/login'
    | '/privacy'
    | '/rreth'
    | '/shkarko'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/speak'
    | '/api/version'
    | '/api/zeri-chat'
    | '/api/zeri-tts'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amarildo-hysa'
    | '/app'
    | '/links'
    | '/login'
    | '/privacy'
    | '/rreth'
    | '/shkarko'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/speak'
    | '/api/version'
    | '/api/zeri-chat'
    | '/api/zeri-tts'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/amarildo-hysa'
    | '/app'
    | '/links'
    | '/login'
    | '/privacy'
    | '/rreth'
    | '/shkarko'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/speak'
    | '/api/version'
    | '/api/zeri-chat'
    | '/api/zeri-tts'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmarildoHysaRoute: typeof AmarildoHysaRoute
  AppRoute: typeof AppRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RrethRoute: typeof RrethRoute
  ShkarkoRoute: typeof ShkarkoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSpeakRoute: typeof ApiSpeakRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiZeriChatRoute: typeof ApiZeriChatRoute
  ApiZeriTtsRoute: typeof ApiZeriTtsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amarildo-hysa': {
      id: '/amarildo-hysa'
      path: '/amarildo-hysa'
      fullPath: '/amarildo-hysa'
      preLoaderRoute: typeof AmarildoHysaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rreth': {
      id: '/rreth'
      path: '/rreth'
      fullPath: '/rreth'
      preLoaderRoute: typeof RrethRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shkarko': {
      id: '/shkarko'
      path: '/shkarko'
      fullPath: '/shkarko'
      preLoaderRoute: typeof ShkarkoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speak': {
      id: '/api/speak'
      path: '/api/speak'
      fullPath: '/api/speak'
      preLoaderRoute: typeof ApiSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zeri-chat': {
      id: '/api/zeri-chat'
      path: '/api/zeri-chat'
      fullPath: '/api/zeri-chat'
      preLoaderRoute: typeof ApiZeriChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zeri-tts': {
      id: '/api/zeri-tts'
      path: '/api/zeri-tts'
      fullPath: '/api/zeri-tts'
      preLoaderRoute: typeof ApiZeriTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmarildoHysaRoute: AmarildoHysaRoute,
  AppRoute: AppRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RrethRoute: RrethRoute,
  ShkarkoRoute: ShkarkoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSpeakRoute: ApiSpeakRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiZeriChatRoute: ApiZeriChatRoute,
  ApiZeriTtsRoute: ApiZeriTtsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
